improve code

diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -1,2 +1,18 @@
 #!/bin/bash
-python3 "$PYCODE"
+
+# check if PYCODE is set
+if [ -z "$PYCODE" ]; then
+	echo "Error: PYCODE variable is not set."
+	exit 1
+fi
+
+# create a temporary variable
+TEMP_FILE=$(mktemp)
+
+# update temporary variable
+echo $PYCODE >"$TEMP_FILE"
+
+# output value
+python3 $TEMP_FILE
+
+rm $TEMP_FILE
